connection: mem
running_workers:
  - default
  
workers:
  default:
    connection: mem
    concurrency: 1
  nsq:
    connection: nsq
    concurrency: 4

connections:
  nsq:
    type: nsq
    nsqd: 127.0.0.1:4150
    #nsqlookupd: localhost:4161