listen: true
connection: nsq
running_workers:
  - nsq
  
workers:
  default:
    connection: mem
    concurrency: 4
  nsq:
    connection: nsq
    concurrency: 4
    
connections:
  nsq:
    type: nsq # support: nsq, mem
    nsqd: 127.0.0.1:49157
    #nsqlookupd: localhost:4161
  mem:
    type: mem