default: default # env: LOGGING_CHANNEL
channels: 
  default:
    outputs:
      - rotate:///runtime.log # schema supports: rotate, single, file, stdout, stderr
      - stdout
  single:
    outputs:
      - single:///runtime.log
  http:
    outputs:
      - rotate:///http.log
      - stdout
    label: http
  database:
    outputs:
      - rotate:///database.log # rotate:///database.log?time_format=2006-01-02T15 04 05&limit=3