listen: true #env: QUEUE_LISTEN
connection: nsq #env: QUEUE_CONNECTION
running_workers:
  - nsq
  
workers:
  default:
    connection: mem
    concurrency: 4
  nsq:
    connection: nsq
    concurrency: 4
  redis:
    connection: redis
    concurrency: 4  
    
connections:
  nsq:
    driver: nsq # support: nsq, mem, redis
    config:
      nsqd: wsl.local:4150
      #nsqlookupd: localhost:4161
  mem:
    driver: mem
  redis:
    driver: redis
    config:
      connection: queue
      queue: enorith:queue